

services:
  clickhouse:
    image: clickhouse:25.6
    env_file:
      - .env
    ports:
      -  8123:8123
    
  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      -  5432:5432

  mysql:
    image: mysql:9
    env_file:
      - .env
    ports:
      -  3306:3306

  nats:
    image: nats:2
    command:
      - -js
    env_file:
      - .env
    ports:
      -  4222:4222
